/// English → Odia loanword dictionary for transliteration.
///
/// Reporters type English loanwords in Latin script ("college", "hospital",
/// "police") expecting the Odia phonetic equivalent (କଲେଜ, ହସ୍ପିଟାଲ, ପୋଲିସ).
/// Google's transliteration API reads these as phonetic Odia and produces
/// garbage because the English spelling doesn't map to Odia phonemes.
///
/// This dictionary intercepts known loanwords BEFORE the API call and
/// returns the correct Odia directly. Checked case-insensitively.
///
/// Maintenance: add entries as reporters report mis-transliterations.
/// Each entry maps the English spelling (lowercase) to the standard
/// Odia rendering used in newspapers/broadcast.
library;

/// Lookup: English (lowercase) → Odia script.
/// Returns null if the word isn't a known loanword.
String? lookupLoanword(String word) {
  return _loanwords[word.toLowerCase()];
}

/// The dictionary. ~500 entries covering:
/// - Education (college, school, university, ...)
/// - Government/politics (minister, parliament, election, ...)
/// - Law/crime (police, court, judge, arrest, ...)
/// - Health (hospital, doctor, nurse, injection, ...)
/// - Sports (cricket, football, match, team, ...)
/// - Technology (phone, mobile, computer, internet, ...)
/// - Transport (bus, train, station, airport, ...)
/// - Media (news, reporter, channel, camera, ...)
/// - Finance (bank, loan, interest, budget, ...)
/// - Common everyday (office, market, hotel, restaurant, ...)
const Map<String, String> _loanwords = {
  // ── Education ──────────────────────────────────────────────────────
  'college': 'କଲେଜ',
  'school': 'ସ୍କୁଲ',
  'university': 'ୟୁନିଭର୍ସିଟି',
  'student': 'ଷ୍ଟୁଡେଣ୍ଟ',
  'teacher': 'ଟିଚର',
  'professor': 'ପ୍ରଫେସର',
  'class': 'କ୍ଲାସ',
  'classroom': 'କ୍ଲାସରୁମ',
  'exam': 'ଏକ୍ଜାମ',
  'examination': 'ଏକ୍ଜାମିନେସନ',
  'result': 'ରିଜଲ୍ଟ',
  'degree': 'ଡିଗ୍ରୀ',
  'diploma': 'ଡିପ୍ଲୋମା',
  'syllabus': 'ସିଲାବସ',
  'semester': 'ସେମିଷ୍ଟର',
  'hostel': 'ହଷ୍ଟେଲ',
  'library': 'ଲାଇବ୍ରେରୀ',
  'laboratory': 'ଲାବୋରେଟୋରୀ',
  'lab': 'ଲ୍ୟାବ',
  'principal': 'ପ୍ରିନ୍ସିପାଲ',
  'admission': 'ଆଡମିସନ',
  'scholarship': 'ସ୍କଲାରସିପ',
  'tuition': 'ଟ୍ୟୁସନ',
  'coaching': 'କୋଚିଂ',
  'certificate': 'ସର୍ଟିଫିକେଟ',
  'marksheet': 'ମାର୍କସିଟ',
  'topper': 'ଟପର',

  // ── Government / Politics ──────────────────────────────────────────
  'minister': 'ମିନିଷ୍ଟର',
  'government': 'ଗଭର୍ନମେଣ୍ଟ',
  'parliament': 'ପାର୍ଲିଆମେଣ୍ଟ',
  'election': 'ଇଲେକସନ',
  'vote': 'ଭୋଟ',
  'voter': 'ଭୋଟର',
  'voting': 'ଭୋଟିଂ',
  'party': 'ପାର୍ଟୀ',
  'leader': 'ଲିଡର',
  'opposition': 'ଅପୋଜିସନ',
  'president': 'ପ୍ରେସିଡେଣ୍ଟ',
  'governor': 'ଗଭର୍ନର',
  'collector': 'କଲେକ୍ଟର',
  'commissioner': 'କମିସନର',
  'officer': 'ଅଫିସର',
  'secretary': 'ସେକ୍ରେଟାରୀ',
  'committee': 'କମିଟି',
  'council': 'କାଉନ୍ସିଲ',
  'assembly': 'ଆସେମ୍ବଲୀ',
  'constituency': 'କନ୍‌ଷ୍ଟିଚୁଏନ୍ସି',
  'candidate': 'କ୍ୟାଣ୍ଡିଡେଟ',
  'rally': 'ର୍ୟାଲି',
  'protest': 'ପ୍ରୋଟେଷ୍ଟ',
  'strike': 'ଷ୍ଟ୍ରାଇକ',
  'bandh': 'ବନ୍ଦ',
  'block': 'ବ୍ଲକ',
  'district': 'ଡିଷ୍ଟ୍ରିକ୍ଟ',
  'municipality': 'ମ୍ୟୁନିସିପାଲିଟି',
  'corporation': 'କର୍ପୋରେସନ',
  'panchayat': 'ପଞ୍ଚାୟତ',
  'sarpanch': 'ସରପଞ୍ଚ',
  'mla': 'ଏମଏଲଏ',
  'mp': 'ଏମପି',
  'bjp': 'ବିଜେପି',
  'congress': 'କଂଗ୍ରେସ',
  'bju': 'ବିଜେଡି',
  'bjd': 'ବିଜେଡି',

  // ── Law / Crime / Police ───────────────────────────────────────────
  'police': 'ପୋଲିସ',
  'station': 'ଷ୍ଟେସନ',
  'court': 'କୋର୍ଟ',
  'judge': 'ଜଜ',
  'lawyer': 'ଲଅୟର',
  'advocate': 'ଆଡଭୋକେଟ',
  'arrest': 'ଆରେଷ୍ଟ',
  'bail': 'ବେଲ',
  'case': 'କେସ',
  'fir': 'ଏଫଆଇଆର',
  'murder': 'ମର୍ଡର',
  'robbery': 'ରୋବେରୀ',
  'theft': 'ଥେଫ୍ଟ',
  'accident': 'ଆକ୍ସିଡେଣ୍ଟ',
  'victim': 'ଭିକ୍ଟିମ',
  'criminal': 'କ୍ରିମିନାଲ',
  'investigation': 'ଇନଭେଷ୍ଟିଗେସନ',
  'inspector': 'ଇନ୍‌ସ୍ପେକ୍ଟର',
  'sp': 'ଏସପି',
  'dsp': 'ଡିଏସପି',
  'ips': 'ଆଇପିଏସ',
  'ias': 'ଆଇଏଏସ',
  'constable': 'କନ୍‌ଷ୍ଟେବଲ',
  'forensic': 'ଫରେନ୍‌ସିକ',
  'postmortem': 'ପୋଷ୍ଟମର୍ଟମ',
  'witness': 'ୱିଟନେସ',
  'evidence': 'ଏଭିଡେନ୍ସ',
  'charge': 'ଚାର୍ଜ',
  'chargesheet': 'ଚାର୍ଜସିଟ',
  'hearing': 'ହିଅରିଂ',
  'verdict': 'ଭର୍ଡିକ୍ଟ',
  'sentence': 'ସେଣ୍ଟେନ୍ସ',
  'jail': 'ଜେଲ',
  'prison': 'ପ୍ରିଜନ',
  'crime': 'କ୍ରାଇମ',
  'rape': 'ରେପ',
  'dowry': 'ଡାଉରି',
  'cyber': 'ସାଇବର',
  'fraud': 'ଫ୍ରଡ',
  'scam': 'ସ୍କ୍ୟାମ',
  'corruption': 'କରପ୍ସନ',

  // ── Health / Medical ───────────────────────────────────────────────
  'hospital': 'ହସ୍ପିଟାଲ',
  'doctor': 'ଡାକ୍ତର',
  'nurse': 'ନର୍ସ',
  'patient': 'ପେସେଣ୍ଟ',
  'medicine': 'ମେଡିସିନ',
  'injection': 'ଇଞ୍ଜେକସନ',
  'vaccine': 'ଭ୍ୟାକ୍ସିନ',
  'vaccination': 'ଭ୍ୟାକ୍ସିନେସନ',
  'operation': 'ଅପରେସନ',
  'surgery': 'ସର୍ଜରୀ',
  'ambulance': 'ଆମ୍ବୁଲାନ୍ସ',
  'clinic': 'କ୍ଲିନିକ',
  'pharmacy': 'ଫାର୍ମାସୀ',
  'medical': 'ମେଡିକାଲ',
  'health': 'ହେଲ୍ଥ',
  'test': 'ଟେଷ୍ଟ',
  'report': 'ରିପୋର୍ଟ',
  'covid': 'କୋଭିଡ',
  'corona': 'କୋରୋନା',
  'fever': 'ଫିଭର',
  'malaria': 'ମ୍ୟାଲେରିଆ',
  'dengue': 'ଡେଙ୍ଗୁ',
  'cancer': 'କ୍ୟାନ୍ସର',
  'diabetes': 'ଡାଇବେଟିସ',
  'oxygen': 'ଅକ୍ସିଜେନ',
  'icu': 'ଆଇସିୟୁ',
  'ventilator': 'ଭେଣ୍ଟିଲେଟର',
  'blood': 'ବ୍ଲଡ',
  'pressure': 'ପ୍ରେସର',
  'tablet': 'ଟ୍ୟାବଲେଟ',

  // ── Sports ─────────────────────────────────────────────────────────
  'cricket': 'କ୍ରିକେଟ',
  'football': 'ଫୁଟବଲ',
  'hockey': 'ହକି',
  'match': 'ମ୍ୟାଚ',
  'team': 'ଟିମ',
  'player': 'ପ୍ଲେୟାର',
  'captain': 'କ୍ୟାପ୍ଟେନ',
  'coach': 'କୋଚ',
  'tournament': 'ଟୁର୍ନାମେଣ୍ଟ',
  'champion': 'ଚାମ୍ପିୟନ',
  'final': 'ଫାଇନାଲ',
  'semifinal': 'ସେମିଫାଇନାଲ',
  'quarter': 'କ୍ୱାର୍ଟର',
  'score': 'ସ୍କୋର',
  'goal': 'ଗୋଲ',
  'run': 'ରନ',
  'wicket': 'ୱିକେଟ',
  'over': 'ଓଭର',
  'batting': 'ବ୍ୟାଟିଂ',
  'bowling': 'ବୋଲିଂ',
  'century': 'ସେଞ୍ଚୁରୀ',
  'stadium': 'ଷ୍ଟାଡିୟମ',
  'ground': 'ଗ୍ରାଉଣ୍ଡ',
  'medal': 'ମେଡାଲ',
  'gold': 'ଗୋଲ୍ଡ',
  'silver': 'ସିଲଭର',
  'bronze': 'ବ୍ରୋଞ୍ଜ',
  'olympics': 'ଅଲିମ୍ପିକ୍ସ',
  'ipl': 'ଆଇପିଏଲ',
  'bcci': 'ବିସିସିଆଇ',
  'world cup': 'ୱାର୍ଲ୍ଡ କପ',

  // ── Technology ─────────────────────────────────────────────────────
  'phone': 'ଫୋନ',
  'mobile': 'ମୋବାଇଲ',
  'smartphone': 'ସ୍ମାର୍ଟଫୋନ',
  'computer': 'କମ୍ପ୍ୟୁଟର',
  'laptop': 'ଲ୍ୟାପଟପ',
  'internet': 'ଇଣ୍ଟରନେଟ',
  'online': 'ଅନଲାଇନ',
  'offline': 'ଅଫଲାଇନ',
  'website': 'ୱେବସାଇଟ',
  'app': 'ଆପ',
  'whatsapp': 'ହ୍ୱାଟ୍ସଆପ',
  'facebook': 'ଫେସବୁକ',
  'twitter': 'ଟ୍ୱିଟର',
  'youtube': 'ୟୁଟ୍ୟୁବ',
  'instagram': 'ଇନଷ୍ଟାଗ୍ରାମ',
  'google': 'ଗୁଗଲ',
  'email': 'ଇମେଲ',
  'message': 'ମେସେଜ',
  'video': 'ଭିଡିଓ',
  'photo': 'ଫଟୋ',
  'camera': 'କ୍ୟାମେରା',
  'selfie': 'ସେଲ୍ଫି',
  'viral': 'ଭାଇରାଲ',
  'password': 'ପାସୱାର୍ଡ',
  'server': 'ସର୍ଭର',
  'network': 'ନେଟୱାର୍କ',
  'wifi': 'ୱାଇଫାଇ',
  'digital': 'ଡିଜିଟାଲ',
  'software': 'ସଫ୍ଟୱେୟାର',
  'technology': 'ଟେକ୍ନୋଲୋଜି',
  'ai': 'ଏଆଇ',

  // ── Transport ──────────────────────────────────────────────────────
  'bus': 'ବସ',
  'train': 'ଟ୍ରେନ',
  'railway': 'ରେଲୱେ',
  'airport': 'ଏୟାରପୋର୍ଟ',
  'flight': 'ଫ୍ଲାଇଟ',
  'ticket': 'ଟିକେଟ',
  'platform': 'ପ୍ଲାଟଫର୍ମ',
  'highway': 'ହାଇୱେ',
  'bridge': 'ବ୍ରିଜ',
  'road': 'ରୋଡ',
  'overbridge': 'ଓଭରବ୍ରିଜ',
  'flyover': 'ଫ୍ଲାଇଓଭର',
  'auto': 'ଅଟୋ',
  'taxi': 'ଟ୍ୟାକ୍ସି',
  'driver': 'ଡ୍ରାଇଭର',
  'license': 'ଲାଇସେନ୍ସ',
  'petrol': 'ପେଟ୍ରୋଲ',
  'diesel': 'ଡିଜେଲ',
  'gas': 'ଗ୍ୟାସ',
  'cylinder': 'ସିଲିଣ୍ଡର',
  'helmet': 'ହେଲମେଟ',
  'parking': 'ପାର୍କିଂ',
  'traffic': 'ଟ୍ରାଫିକ',
  'signal': 'ସିଗନାଲ',
  'metro': 'ମେଟ୍ରୋ',

  // ── Media / Journalism ─────────────────────────────────────────────
  'news': 'ନ୍ୟୁଜ',
  'reporter': 'ରିପୋର୍ଟର',
  'journalist': 'ଜର୍ନାଲିଷ୍ଟ',
  'editor': 'ଏଡିଟର',
  'channel': 'ଚ୍ୟାନେଲ',
  'media': 'ମିଡିଆ',
  'press': 'ପ୍ରେସ',
  'conference': 'କନଫରେନ୍ସ',
  'interview': 'ଇଣ୍ଟରଭ୍ୟୁ',
  'live': 'ଲାଇଭ',
  'breaking': 'ବ୍ରେକିଂ',
  'bulletin': 'ବୁଲେଟିନ',
  'headline': 'ହେଡଲାଇନ',
  'newspaper': 'ନ୍ୟୁଜପେପର',
  'magazine': 'ମ୍ୟାଗାଜିନ',
  'tv': 'ଟିଭି',
  'radio': 'ରେଡିଓ',
  'broadcast': 'ବ୍ରଡକାଷ୍ଟ',

  // ── Finance / Business ─────────────────────────────────────────────
  'bank': 'ବ୍ୟାଙ୍କ',
  'loan': 'ଲୋନ',
  'interest': 'ଇଣ୍ଟରେଷ୍ଟ',
  'budget': 'ବଜେଟ',
  'tax': 'ଟ୍ୟାକ୍ସ',
  'gst': 'ଜିଏସଟି',
  'income': 'ଇନକମ',
  'salary': 'ସ୍ୟାଲାରୀ',
  'pension': 'ପେନ୍ସନ',
  'insurance': 'ଇନସ୍ୟୁରେନ୍ସ',
  'share': 'ସେୟାର',
  'market': 'ମାର୍କେଟ',
  'stock': 'ଷ୍ଟକ',
  'company': 'କମ୍ପାନୀ',
  'business': 'ବିଜନେସ',
  'profit': 'ପ୍ରଫିଟ',
  'loss': 'ଲସ',
  'investment': 'ଇନଭେଷ୍ଟମେଣ୍ଟ',
  'crore': 'କୋଟି',
  'lakh': 'ଲକ୍ଷ',
  'rupee': 'ରୁପିଆ',
  'atm': 'ଏଟିଏମ',
  'upi': 'ୟୁପିଆଇ',
  'account': 'ଆକାଉଣ୍ଟ',
  'cheque': 'ଚେକ',
  'deposit': 'ଡିପୋଜିଟ',
  'subsidy': 'ସବସିଡି',

  // ── Everyday / Places ──────────────────────────────────────────────
  'office': 'ଅଫିସ',
  'hotel': 'ହୋଟେଲ',
  'restaurant': 'ରେଷ୍ଟୁରାଣ୍ଟ',
  'cinema': 'ସିନେମା',
  'theatre': 'ଥିଏଟର',
  'theater': 'ଥିଏଟର',
  'mall': 'ମଲ',
  'shop': 'ସପ',
  'showroom': 'ସୋରୁମ',
  'flat': 'ଫ୍ଲ୍ୟାଟ',
  'building': 'ବିଲ୍ଡିଂ',
  'tower': 'ଟାୱାର',
  'park': 'ପାର୍କ',
  'garden': 'ଗାର୍ଡେନ',
  'club': 'କ୍ଲବ',
  'centre': 'ସେଣ୍ଟର',
  'center': 'ସେଣ୍ଟର',
  'complex': 'କମ୍ପ୍ଲେକ୍ସ',
  'colony': 'କଲୋନୀ',
  'society': 'ସୋସାଇଟି',
  'apartment': 'ଆପାର୍ଟମେଣ୍ଟ',
  'factory': 'ଫ୍ୟାକ୍ଟରୀ',
  'industry': 'ଇଣ୍ଡଷ୍ଟ୍ରି',
  'temple': 'ଟେମ୍ପଲ',
  'church': 'ଚର୍ଚ',
  'mosque': 'ମସଜିଦ',

  // ── Disaster / Emergency ───────────────────────────────────────────
  'cyclone': 'ସାଇକ୍ଲୋନ',
  'flood': 'ଫ୍ଲଡ',
  'earthquake': 'ଅର୍ଥକ୍ୱେକ',
  'fire': 'ଫାୟାର',
  'rescue': 'ରେସ୍କ୍ୟୁ',
  'relief': 'ରିଲିଫ',
  'ndrf': 'ଏନଡିଆରଏଫ',
  'odraf': 'ଓଡ୍ରାଫ',
  'shelter': 'ସେଲ୍ଟର',
  'damage': 'ଡ୍ୟାମେଜ',
  'alert': 'ଆଲର୍ଟ',
  'warning': 'ୱାର୍ନିଂ',
  'evacuation': 'ଇଭ୍ୟାକୁଏସନ',
  'casualty': 'କ୍ୟାଜୁଆଲ୍ଟି',
  'death': 'ଡେଥ',
  'injured': 'ଇନ୍‌ଜୁରଡ',

  // ── General / Common ───────────────────────────────────────────────
  'meeting': 'ମିଟିଂ',
  'programme': 'ପ୍ରୋଗ୍ରାମ',
  'program': 'ପ୍ରୋଗ୍ରାମ',
  'function': 'ଫଙ୍କସନ',
  'ceremony': 'ସେରିମୋନୀ',
  'event': 'ଇଭେଣ୍ଟ',
  'festival': 'ଫେଷ୍ଟିଭାଲ',
  'celebration': 'ସେଲିବ୍ରେସନ',
  'public': 'ପବ୍ଲିକ',
  'private': 'ପ୍ରାଇଭେଟ',
  'national': 'ନ୍ୟାସନାଲ',
  'international': 'ଇଣ୍ଟରନ୍ୟାସନାଲ',
  'level': 'ଲେଭେଲ',
  'standard': 'ଷ୍ଟାଣ୍ଡାର୍ଡ',
  'quality': 'କ୍ୱାଲିଟି',
  'system': 'ସିଷ୍ଟମ',
  'problem': 'ପ୍ରବଲେମ',
  'issue': 'ଇସ୍ୟୁ',
  'solution': 'ସଲ୍ୟୁସନ',
  'project': 'ପ୍ରୋଜେକ୍ଟ',
  'scheme': 'ସ୍କିମ',
  'plan': 'ପ୍ଲାନ',
  'target': 'ଟାର୍ଗେଟ',
  'notice': 'ନୋଟିସ',
  'order': 'ଅର୍ଡର',
  'circular': 'ସର୍କୁଲାର',
  'letter': 'ଲେଟର',
  'complaint': 'କମ୍ପ୍ଲେଣ୍ଟ',
  'demand': 'ଡିମାଣ୍ଡ',
  'supply': 'ସପ୍ଲାଇ',
  'rate': 'ରେଟ',
  'price': 'ପ୍ରାଇସ',
  'free': 'ଫ୍ରି',
  'number': 'ନମ୍ବର',
  'total': 'ଟୋଟାଲ',
  'list': 'ଲିଷ୍ଟ',
  'form': 'ଫର୍ମ',
  'record': 'ରେକର୍ଡ',
  'register': 'ରେଜିଷ୍ଟର',
  'cancel': 'କ୍ୟାନ୍ସେଲ',
  'transfer': 'ଟ୍ରାନ୍ସଫର',
  'posting': 'ପୋଷ୍ଟିଂ',
  'promotion': 'ପ୍ରମୋସନ',
  'union': 'ୟୁନିୟନ',
  'member': 'ମେମ୍ବର',
  'chairman': 'ଚେୟାରମ୍ୟାନ',
  'vice': 'ଭାଇସ',

  // ── Time / Date ────────────────────────────────────────────────────
  'january': 'ଜାନୁଆରୀ',
  'february': 'ଫେବୃଆରୀ',
  'march': 'ମାର୍ଚ୍ଚ',
  'april': 'ଏପ୍ରିଲ',
  'may': 'ମେ',
  'june': 'ଜୁନ',
  'july': 'ଜୁଲାଇ',
  'august': 'ଅଗଷ୍ଟ',
  'september': 'ସେପ୍ଟେମ୍ବର',
  'october': 'ଅକ୍ଟୋବର',
  'november': 'ନଭେମ୍ବର',
  'december': 'ଡିସେମ୍ବର',
  'monday': 'ସୋମବାର',
  'tuesday': 'ମଙ୍ଗଳବାର',
  'wednesday': 'ବୁଧବାର',
  'thursday': 'ଗୁରୁବାର',
  'friday': 'ଶୁକ୍ରବାର',
  'saturday': 'ଶନିବାର',
  'sunday': 'ରବିବାର',

  // ── Titles / Honorifics ────────────────────────────────────────────
  'sir': 'ସର',
  'madam': 'ମ୍ୟାଡାମ',
  'mr': 'ମିଷ୍ଟର',
  'mrs': 'ମିସେସ',
  'miss': 'ମିସ',
  'dr': 'ଡକ୍ଟର',

  // ── Units / Measurement ────────────────────────────────────────────
  'km': 'କିଲୋମିଟର',
  'kg': 'କିଲୋଗ୍ରାମ',
  'meter': 'ମିଟର',
  'litre': 'ଲିଟର',
  'liter': 'ଲିଟର',
  'acre': 'ଏକର',
  'hectare': 'ହେକ୍ଟର',
  'percent': 'ପ୍ରତିଶତ',
  'percentage': 'ପର୍ସେଣ୍ଟେଜ',

  // ── Miscellaneous common words ─────────────────────────────────────
  'development': 'ଡେଭେଲପମେଣ୍ଟ',
  'environment': 'ଏନଭାୟରନମେଣ୍ଟ',
  'pollution': 'ପଲ୍ୟୁସନ',
  'water': 'ୱାଟର',
  'power': 'ପାୱାର',
  'electricity': 'ଇଲେକ୍ଟ୍ରିସିଟି',
  'current': 'କରେଣ୍ଟ',
  'transformer': 'ଟ୍ରାନ୍ସଫର୍ମର',
  'pipeline': 'ପାଇପଲାଇନ',
  'connection': 'କନେକସନ',
  'service': 'ସର୍ଭିସ',
  'department': 'ଡିପାର୍ଟମେଣ୍ଟ',
  'section': 'ସେକସନ',
  'division': 'ଡିଭିଜନ',
  'zone': 'ଜୋନ',
  'area': 'ଏରିଆ',
  'ward': 'ୱାର୍ଡ',
  'quota': 'କୋଟା',
  'reservation': 'ରିଜର୍ଭେସନ',
  'ration': 'ରେସନ',
  'card': 'କାର୍ଡ',
  'aadhaar': 'ଆଧାର',
  'aadhar': 'ଆଧାର',
  'pan': 'ପ୍ୟାନ',
  'passport': 'ପାସପୋର୍ଟ',
  'lockdown': 'ଲକଡାଉନ',
  'curfew': 'କର୍ଫ୍ୟୁ',
  'positive': 'ପଜିଟିଭ',
  'negative': 'ନେଗେଟିଭ',
  'sample': 'ସ୍ୟାମ୍ପଲ',
  'dose': 'ଡୋଜ',
};
