steps:
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -f
    - Dockerfile.fetcher
    - -t
    - ${_IMAGE}
    - .
images:
- ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _IMAGE: asia-south1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/widget-fetcher:latest
